mqtt:
  hostname: 127.0.0.1
  port: 1883
  user: test
  password: test
deviceName: test
client_id: test
timezone: Asia/Ho_chi_Minh
update_interval: 60 #Defaults to 60
check_wifi_strength: false
check_wifi_ssid: false
check_available_updates: false
